version: '3.9'

volumes:
  mysqlData:

services:
  db:
    container_name: db
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_USER_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - mysqlData:/var/lib/mysql
